### ISSUE TITLE
Memory usage skyrockets when doing the compression

### ISSUE THREAD

**Issue by brucem1976** [Donaldcwl/browser-image-compression#20] opened 2019-07-23 19:49 UTC
So the compression is working, but memory often goes through the roof - for example, compressing a 40MB jpg spikes my browser's memory usage up to 2GB. This causes crashes and inconsistent behaviour on mobile browsers.

After the process is finished, there is also about 400MB more memory being used by the browser, which never gets cleaned up and released.

Is there anything that I can do to manage the amount of a memory this process will use?

**Comment by Donaldcwl** [comment] 2020-03-16 06:21
Duplicate of #41

**Closed by Donaldcwl** 2020-03-16 06:21 UTC
