### ISSUE TITLE
Output size is larger than input size

### ISSUE THREAD

**Issue by rbozan** [Donaldcwl/browser-image-compression#57] opened 2020-05-08 08:24 UTC
![Schermafdruk van 2020-05-08 10-22-25](https://user-images.githubusercontent.com/7997154/81386773-dd380c00-9115-11ea-9592-404ce8935113.png)

Using the example on https://donaldcwl.github.io/browser-image-compression/example/basic.html, the input size is 0.89mb and output size is 2.32mb using this image:

![telefoon](https://user-images.githubusercontent.com/7997154/81386648-acf06d80-9115-11ea-8009-84b55ebfca0a.png)

**Comment by Donaldcwl** [comment] 2020-05-18 17:44
@rbozan Can you provide the platform and browser version that you are using. I cannot reproduce your issue.
![2020-05-19_01-44-00](https://user-images.githubusercontent.com/11781337/82243474-43bcf580-9972-11ea-9c37-a3891407fc06.png)

**Comment by rbozan** [comment] 2020-05-18 17:50
I think you have to remove maxwidth input, so only maxsizemb to 1

**Comment by zehawki** [comment] 2020-11-07 22:26
I can confirm similar as well. input size = 470KB. Output is 2MB, While constraint is 0.1MB

![image](https://user-images.githubusercontent.com/8095144/98452554-3ee53b80-2176-11eb-9c3b-0061df54437b.png)

**Comment by Donaldcwl** [comment] 2020-11-08 10:57
@zehawki Would you mind uploading the image(s) you have tested with the problem?

**Comment by zehawki** [comment] 2020-11-08 13:34
Please see here https://gofile.io/d/QLRH8X

**Comment by Donaldcwl** [comment] 2020-11-08 15:11
@zehawki Thanks, this issue has been fixed in the new version (v1.0.13).

**Closed** 2020-11-08 15:14 UTC
